version: '3.9'
services:
    admin:
      build:
        context: .
        dockerfile: Dockerfile
      command: 'php artisan serve --host=0.0.0.0'
      volumes:
        - .:/app
      ports:
        - '8001:8000'
#      networks:
#        - rabbitmq
      depends_on:
        - admin-db

    admin_queue:
      build:
        context: .
        dockerfile: Dockerfile
      command: 'php artisan queue:work'
#      networks:
#          - rabbitmq
      depends_on:
        - admin-db

    admin-db:
      image: mysql:8.0.0
      environment:
        MYSQL_DATABASE: admin
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./storage/dbdata:/var/lib/mysql
      ports:
        - "33064:3306"
#      networks:
#          - rabbitmq

#networks:
#    rabbitmq:
